### ISSUE TITLE
Arduino Uno Compatibility

### ISSUE THREAD

**Issue by RicardoPires19** [onelife/Arduino_RT-Thread#1]
Is this library compatible with Arduino UNO? I'm trying to make it work, but I get an error that says:

In file included from Arduino\libraries\RT_Thread-0.7.3\src/include/rtlibc.h:15:0,
                 from Arduino\libraries\RT_Thread-0.7.3\src/include/rtdef.h:1066,
                 from Arduino\libraries\RT_Thread-0.7.3\src/include/rtthread.h:24,
                 from Arduino\libraries\RT_Thread-0.7.3\src/rtt.h:9,
                 from Arduino\libraries\RT_Thread-0.7.3\examples\Blink\Blink.ino:6:

Arduino\libraries\RT_Thread-0.7.3\src/include/libc/libc_stat.h:14:22: fatal error: sys/stat.h: No such file or directory

compilation terminated.

exit status 1
Error compiling for board Arduino/Genuino Uno.

**Comment by onelife** [comment]
Hi @RicardoPires19,

The library currently only supports SAMD (ARM Cortex-M0, e.g. Arduino ZERO) and SAM (ARM Cortex-M3, e.g. Arduino DUE) boards.
And I am sorry that there is no plan to support AVR (e.g.  Arduino UNO) boards.
