### ISSUE TITLE
这个是官方支持的吗

### ISSUE THREAD

**Issue by sogwms** [onelife/Arduino_RT-Thread#2]

**Comment by onelife** [comment]
虽然这不是一个 issue，但十分乐意回答。下次仁兄可以选择以下管道来沟通（都是“官方”管道:wink:），@onelife 即可。（我会尽快更新一下 README.md 。）

- [gitter](https://gitter.im/RT-Thread/rt-thread)
- [slack](https://rtthread.slack.com)

回答问题：
这个仓库目前是我一个人维护的。“官方”的仓库，我想应该都是由 [RT-Thread](https://github.com/RT-Thread) 账号发布的吧。
