### ISSUE TITLE
[GUIDE/TUTORIAL] Sipeed using Arduino IDE

### ISSUE THREAD

**Issue by sandeepansg** [onelife/Arduino_RT-Thread#3]
Longan Nano is not showing up on any COM port
How do to upload example codes from this library to Sipeed Longan Nano ?

**Comment by onelife** [comment]
According to [this doc](https://longan.sipeed.com/en/get_started/blink.html), there are 3 options to download code. I guess you want the "USB DFU" method.

**Comment by sandeepansg** [comment]
Thank you @onelife for responding.
So, if I use your core on Arduino IDE, will it require me to use external dfu uploader, like the one described on the cited document ?

**Comment by onelife** [comment]
After adding the [BSP url](https://github.com/sipeed/Longduino/blob/master/README.md) to Arduino IDE, those options will be available.
